\begin{equation*}
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0
\end{vmatrix}
\end{equation*}

## From: https://www.coursera.org/learn/robotics-perception/home/welcome

# Camera Modelling

### Thin lens

![alt text](thinLens.png "Title")

\begin{equation*}
\frac{1}{f} = \frac{1}{a} + \frac{1}{b}
\end{equation*}

Where:

f = focal length,<br>
a = Distance from lens to the object<br>
b = Distance from lens to the image plane
<br><br>
\begin{equation*}
\frac{Y}{a} = \frac{y}{b}
\end{equation*}

Where:

Y is the size of an object,<br>
y is the size of that object on the image plane.

### Camera/world geometry


![alt text](worldCameraCoords.png "Title")


### Perspective projection


![alt text](vanishingProjection.png "Title")

![alt text](vanishingLines.png "Title")

![alt text](projectivePlane.png "Title")


### Homogeneous Coordinates

Image plane [x, y, 1] is located 1 unit away from the origin (at [0, 0, 0])

![alt text](pointCoordinates.png "Title")

![alt text](projectiveLines.png "Title")

Dot product = 0

$a$, $b$ & $c$ are the surface normal of the plane created between 0, 0, 0 and any two points on the line.

![alt text](lineRepresentation.png "Title")

![alt text](lineExample1.png "Title")

$\theta$ is the angle from the origin of the normal to the line (0, 0) to the line.<br>
$\rho$ is the length of the normal from the origin to the line<br>


$$a = cos(0.3 * \pi)$$
$$b = sin(0.3 * \pi)$$
$$c = -\rho$$

In [1]:
import math
a = math.cos(0.3 * math.pi)
b = math.sin(0.3 * math.pi)
c = -136.6

print "a = ", a, ", b = ", b, ", c = ", c;

a =  0.587785252292 , b =  0.809016994375 , c =  -136.6



![alt text](lineExample2.png "Title")

In [2]:
a = math.cos(0.42*math.pi)
b = math.sin(0.42*math.pi)
c = -267.0

print "a = ", a, ", b = ", b, ", c = ", c;

a =  0.248689887165 , b =  0.968583161129 , c =  -267.0


![alt text](linePassing.png "Title") 

Consider two rays: one from the origin to $P_1$, and the other from the origin to $P_2$. The first forms the 3D vector $x$, the second form the 3D vector $x'$. In this case, the vector normal to the plane defined by these two vectors is a line $l$ given by the cross product: $$l = x \times x'$$

![alt text](crossExample.png "Title") 

Point P1 is at $[42.0, 142.0, 1]$ (Image plane defined to be at $z=1$).

Point P2 is at $[218, 13.0, 1]$

Plane normal (normalised in XY only) of the line defined between these two points and the origin is $[0.591, 0.807, -139.36]$

In [3]:
import numpy as np

def normaliseXYOnly(vec):
    
    length = 0
    for x in range(0, len(vec)-1):
        length += vec[x]**2
    
    length = math.sqrt(length)

    for x in range(0, len(vec)):
        vec[x] = vec[x]/length
    
    return vec

def calculatePlaneNormalFrom2DImagePoints(point1, point2):
    
    #convert to homogeneous coords here by adding z=1
    point1.append(1)
    point2.append(1)
    
    planeNormal = np.cross(point1, point2)
    planeNormal = normaliseXYOnly(planeNormal)
    
    print("plane normal for points {} and {} is {}".format(point1, point2, planeNormal))
    return planeNormal


P1 = [42.0, 142.0]
P2 = [218.0, 13.0]


l = calculatePlaneNormalFrom2DImagePoints(P1, P2)


plane normal for points [42.0, 142.0, 1] and [218.0, 13.0, 1] is [   0.59116497    0.80655066 -139.35912314]


### Intersection of two lines

![alt text](intersectionOfTwoLines.png "Title") 

If two lines on the image intersect at P, then a line from the origin to P will be perpendicular to a plane defined by the surface normal of the first line and the surface normal of the second line.
In other words, given two lines on the image, you can calculate their point of intersection by taking the cross product of the plane normals created by the two lines.

![alt text](lineIntersectionExample.png "Title") 

Given an image with two lines where the first line contains the points [0, 0] & [100, 0], and the second line contains the points [50, 100] & [50, 50], then we would expect an intersection at [50, 0] 

In [4]:
def calculateIntersectionOfTwoLinesFrom2DPoints(Line1Point1, Line1Point2, Line2Point1, Line2Point2):
    
    line1PlaneNormal = calculatePlaneNormalFrom2DImagePoints(Line1Point1, Line1Point2)
    line2PlaneNormal = calculatePlaneNormalFrom2DImagePoints(Line2Point1, Line2Point2)
    
    intersection = np.cross(line2PlaneNormal, line1PlaneNormal)
    
    return intersection
    

In [5]:
def normalise3DVectorToZEquals1(vec):
    
    normalised = [x/vec[2] for x in vec]
    
    return normalised

In [15]:
def calculateIntersectionOfTwoLinesAtImagePlane(L1P1, L1P2, L2P1, L2P2):
    
    intersection = calculateIntersectionOfTwoLinesFrom2DPoints(L1P1, L1P2, L2P1, L2P2)

    if(intersection[2] == 0.0):
        return intersection
    
    intersection = normalise3DVectorToZEquals1(intersection)

    return intersection

In [16]:
L1P1 = [0.0, 0.0]
L1P2 = [100.0, 0.0]
L2P1 = [50.0, 100.0]
L2P2 = [50.0, 50.0]

intersection = calculateIntersectionOfTwoLinesAtImagePlane(L1P1, L1P2, L2P1, L2P2)

print("Intersection is at: {}".format(intersection))

plane normal for points [0.0, 0.0, 1] and [100.0, 0.0, 1] is [ 0.  1.  0.]
plane normal for points [50.0, 100.0, 1] and [50.0, 50.0, 1] is [  1.   0. -50.]
Intersection is at: [50.0, 0.0, 1.0]


Given an image with two lines where the first line contains the points [0, 0] & [100, 100], and the second line contains the points [0, 100] & [100, 0], then we would expect an intersection at [50, 50] on the image plane.

In [17]:
L1P1 = [0.0, 0.0]
L1P2 = [100.0, 100.0]
L2P1 = [0.0, 100.0]
L2P2 = [100.0, 0.0]

intersection = calculateIntersectionOfTwoLinesAtImagePlane(L1P1, L1P2, L2P1, L2P2)

print("Intersection is at: {}".format(intersection))

plane normal for points [0.0, 0.0, 1] and [100.0, 100.0, 1] is [-0.70710678  0.70710678  0.        ]
plane normal for points [0.0, 100.0, 1] and [100.0, 0.0, 1] is [  0.70710678   0.70710678 -70.71067812]
Intersection is at: [50.000000000000014, 50.000000000000014, 1.0]


![alt text](pointLineDuality.png "Title") 
![alt text](pointAtInfinity.png "Title") 

In [22]:
#parallel lines
L1P1 = [10.0, 0.0]
L1P2 = [10.0, 10.0]
L2P1 = [20.0, 0.0]
L2P2 = [20.0, 10.0]

intersection = calculateIntersectionOfTwoLinesAtImagePlane(L1P1, L1P2, L2P1, L2P2)

print('intersection is at infinity if z=0: {}'.format(intersection))
print('lines are parallel in the -y direction')

plane normal for points [0.0, 0.0, 1] and [1.0, 1.0, 1] is [-0.70710678  0.70710678  0.        ]
plane normal for points [0.0, 0.0, 1] and [-1.0, 1.0, 1] is [-0.70710678 -0.70710678  0.        ]
intersection is at infinity if z=0: [-0.0, -0.0, 1.0]
lines are parallel in the -y direction


![alt text](pointAtInfinity2.png "Title") 
![alt text](pointAtInfinity3.png "Title") 

Line pointing to infinity has a plane parallel to the image plane
![alt text](lineAtInfinity.png "Title") 
![alt text](idealPointsAndLines.png "Title") 

## Transformations & Rotations

![alt text](transformationCameraWorldCoords.png "Title") 
![alt text](worldOrCameraCoords.png "Title") 

The point with respect to the camera is the camera rotation * the point with respect to the world + the translation of the camera relative to the world

![alt text](worldCameraCoords2.png "Title") 
![alt text](geometricMeaningOfTranslation.png "Title") 


The first column of the camera rotation matrix is the x-axis of the world with respect to the camera. (r1)
The second column of the camera rotation matrix is the y-axis of the world with respect to the camera. (r2)
The third column of the camera rotation matrix is the z-axis of the world with respect to the camera. (r3)

![alt text](geometricMeaningOfRotation.png "Title") 


In the following example, the world X axis (r1) is opposite to the camera X axis (Xc), so the first column is
$$
        \begin{pmatrix}
        -1 \\
        0 \\
        0 \\
        \end{pmatrix}
$$

The world Y axis (r2) is opposite the camera Z axis (Zc), so the second column is 

$$
        \begin{pmatrix}
        0 \\
        0 \\
        -1 \\
        \end{pmatrix}
$$

and the world Z axis (r3) is opposite the camera Y axis (Yc), so the third column is 


$$
        \begin{pmatrix}
        0 \\
        -1 \\
        0 \\
        \end{pmatrix}
$$

Resulting in the rotation matrix for this example being


$$
        \begin{pmatrix}
        -1 & 0 & 0\\
        0 & 0 & -1\\
        0 & -1 & 0\\
        \end{pmatrix}
$$


![alt text](rotationMatrixExample.png "Title") 


Translation is just the vector from the origin of the CAMERA to the origin of the WORLD.

![alt text](translationMatrixExample.png "Title") 


Make sure that the 3x3 matrix is a rotation matrix - all columns orthogonal $\begin{equation*}
\ R^TR=I
\end{equation*}$ and $\begin{equation*} det(R)= 1 \end{equation*}$
![alt text](confirmRotationMatrix.png "Title") 



In [39]:
r = np.array([[-1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, -1.0, 0.0]])

print(r)

print("This should be == 1: {}".format(np.linalg.det(r)))

print("This should be the identity matrix:\n {}".format(np.matmul(r.T, r)))

[[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]]
This should be == 1: 1.0
This should be the identity matrix:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
